name: Build, Test, Deploy Compliment Bot

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install aws-sam-cli

      - name: Run tests
        run: pytest -q

      - name: Build SAM app
        run: sam build

      - name: Deploy SAM app
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          sam deploy --no-confirm-changeset \
                     --no-fail-on-empty-changeset \
                     --stack-name compliment-bot \
                     --capabilities CAPABILITY_IAM

      - name: Tag production commit
        if: github.ref == 'refs/heads/main'
        run: |
          DATE=$(date -u +'%Y-%m-%d')
          TAG="prod-$DATE"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git tag $TAG
          git push origin $TAG
